name: build and test python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, development ]
  workflow_dispatch:
env:
  PYTHON_VERSION: '3.9'
jobs:
  build-and-test:
    name: build-and-test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install package and requirements
      working-directory: ./Crypto_Scraper/
      run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements.txt
          pip install pytest

    - name: Test
      working-directory: ./Crypto_Scraper/
      run: python -m pytest


